Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "debian/bookworm64"
    vm1.vm.network "private_network", ip: "192.168.56.101"
    vm1.vm.hostname = "vm1"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "debian/bookworm64"
    vm2.vm.network "private_network", ip: "192.168.56.102"
    vm2.vm.hostname = "vm2"
  end

end

